name: Build and Release .NET Framework

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        shell: pwsh
        run: nuget restore "Web-Application-CICD.sln"

      - name: Build solution (Release)
        shell: pwsh
        run: >
          msbuild "Web-Application-CICD.sln"
          /m
          /p:Configuration=Release
          /p:Platform="Any CPU"
          /p:OutDir="${{ github.workspace }}\out\"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out\

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
